#!/bin/bash
sudo curl https://storage.googleapis.com/git-repo-downloads/repo -o /bin/repo
sudo chmod a+rx /bin/repo
git config --global color.ui true
git config --global user.name ci
git config --global user.email ci@ci.ci

mkdir -p ~/.config/rclone
echo $rclone_config > ~/.config/rclone/rclone.conf

tmate -S /tmp/tmate.sock new-session -d               # Launch tmate in a headless mode
tmate -S /tmp/tmate.sock wait tmate-ready             # Blocks until the SSH connection is established
tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}'    # Prints the SSH connection string


cd /tmp
url=https://roms.apon77.workers.dev/junk/compressed/rom.tar.gz
time aria2c $url -x16 -s50 || time aria2c $url -x16 -s50
time tar xf rom.tar.gz
rm -rf rom.tar.gz

cd /tmp/rom

. build/envsetup.sh
lunch aosp_mido-user
export CCACHE_DIR=/tmp/ccache
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1
ccache -M 20G # It took only 6.4GB for mido
ccache -o compression=true # Will save times and data to download and upload ccache, also negligible performance issue
ccache -z # Clear old stats, so monitor script will provide real ccache statistics

make bootimage -j4
