name: aosp
on:
  push:
  workflow_dispatch:
jobs:
  job1:
    name: aosp
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: slim
      run: |
       ./slim &
    - name: sync
      run: |
       ./sync
    - name: build
      run: |
       ./build
