name: aosp
on:
  push:
  workflow_dispatch:
jobs:
  job1:
    name: aosp
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        parts: [init, bootimage, api-stubs-docs, system-api-stubs-docs, test-api-stubs-docs, app_process, services, framework, framework-res, libandroid_runtime, libbinder, device/xiaomi/mido, vendor/xiaomi/mido, frameworks]
    env:
      parts: ${{ matrix.parts }}
    steps:
    - uses: actions/checkout@v2
    - name: parts
      run: |
        echo $parts
    - name: slim
      run: |
        ./slim
    - name: swap
      run: |
        ./swap
    - name: sync
      run: |
        ./sync
    - name: build
      run: |
        ./build
