name: combined
on:
  push:
  workflow_dispatch:
jobs:
  job1:
    name: combined
    runs-on: ubuntu-20.04
    env:
      rclone_config: ${{ secrets.RCLONE_CONFIG }}
    continue-on-error: true
    steps:
    - uses: actions/checkout@v2
    - name: swap
      run: |
        ./swap
    - name: download ccache
      continue-on-error: true
      run: |
        ./download_ccache
    - uses: rokibhasansagar/slimhub_actions@main
    - name: packages
      run: |
        ./packages &
    - name: sync
      run: |
        ./sync
    - name: build
      continue-on-error: true
      run: |
        ./build
    - name: upload ccache
      run: |
        ./upload_ccache
