name: out
on:
  push:
  workflow_dispatch:
jobs:
  job1:
    name: out
    runs-on: ubuntu-20.04
    env:
      rclone_config: ${{ secrets.RCLONE_CONFIG }}
    continue-on-error: true
    steps:
    - uses: actions/checkout@v2
    - name: swap
      run: |
        ./swap
    - uses: rokibhasansagar/slimhub_actions@main
    - name: packages
      run: |
        ./packages &
    - name: build
      run: |
        ./build
